
function [ horz, vert ] = extractPicrossFromWebpbn( address )

% JPATH = { ...
%     'C:\picross\selenium\selenium-java-2.33.0.jar', ...
%     'C:\picross\selenium\libs\apache-mime4j-0.6.jar', ...
%     'C:\picross\selenium\libs\bsh-1.3.0.jar', ...
%     'C:\picross\selenium\libs\cglib-nodep-2.1_3.jar', ...
%     'C:\picross\selenium\libs\commons-codec-1.6.jar', ...
%     'C:\picross\selenium\libs\commons-collections-3.2.1.jar', ...
%     'C:\picross\selenium\libs\commons-exec-1.1.jar', ...
%     'C:\picross\selenium\libs\commons-io-2.2.jar', ...
%     'C:\picross\selenium\libs\commons-jxpath-1.3.jar', ...
%     'C:\picross\selenium\libs\commons-lang3-3.1.jar', ...
%     'C:\picross\selenium\libs\commons-logging-1.1.1.jar', ...
%     'C:\picross\selenium\libs\cssparser-0.9.9.jar', ...
%     'C:\picross\selenium\libs\guava-14.0.jar', ...
%     'C:\picross\selenium\libs\hamcrest-core-1.3.jar', ...
%     'C:\picross\selenium\libs\hamcrest-library-1.3.jar', ...
%     'C:\picross\selenium\libs\htmlunit-2.12.jar', ...
%     'C:\picross\selenium\libs\htmlunit-core-js-2.12.jar', ...
%     'C:\picross\selenium\libs\httpclient-4.2.1.jar', ...
%     'C:\picross\selenium\libs\httpcore-4.2.1.jar', ...
%     'C:\picross\selenium\libs\httpmime-4.2.1.jar', ...
%     'C:\picross\selenium\libs\ini4j-0.5.2.jar', ...
%     'C:\picross\selenium\libs\jcommander-1.29.jar', ...
%     'C:\picross\selenium\libs\jetty-websocket-8.1.8.jar', ...
%     'C:\picross\selenium\libs\jna-3.4.0.jar', ...
%     'C:\picross\selenium\libs\jna-platform-3.4.0.jar', ...
%     'C:\picross\selenium\libs\json-20080701.jar', ...
%     'C:\picross\selenium\libs\junit-dep-4.11.jar', ...
%     'C:\picross\selenium\libs\nekohtml-1.9.17.jar', ...
%     'C:\picross\selenium\libs\netty-3.5.7.Final.jar', ...
%     'C:\picross\selenium\libs\operadriver-1.3.jar', ...
%     'C:\picross\selenium\libs\phantomjsdriver-1.0.3.jar', ...
%     'C:\picross\selenium\libs\protobuf-java-2.4.1.jar', ...
%     'C:\picross\selenium\libs\sac-1.3.jar', ...
%     'C:\picross\selenium\libs\serializer-2.7.1.jar', ...
%     'C:\picross\selenium\libs\testng-6.8.jar', ...
%     'C:\picross\selenium\libs\xalan-2.7.1.jar', ...
%     'C:\picross\selenium\libs\xercesImpl-2.10.0.jar', ...
%     'C:\picross\selenium\libs\xml-apis-1.4.01.jar' };
% javaaddpath( JPATH );

driver = org.openqa.selenium.firefox.FirefoxDriver();
driver.get( address );
driver.switchTo.frame( 'main' );

    function clues = extractClues( elts )
        
        nbImgs = elts.size();
        
        cluesv = zeros( 1, elts.size() );
        
        for i = 1:nbImgs
            
            title = char( elts.get(i-1).getAttribute( 'title' ) );
            num = str2double( regexp( title, '\<\d*\>', 'match' ) );
            
            if isempty( num )
                cluesv(i) = NaN;
            else
                cluesv(i) = num;
            end
            
        end
        
        ind = 1; new = true;
        clues = { [] };
        for i = 1:nbImgs
            
            if ~isnan( cluesv(i) )
                new = false;
                clues{ind} = [ clues{ind} cluesv(i) ];
            elseif ~new
                ind = ind + 1;
                clues{ind} = [];
                new = true;
            end
            
        end
        
    end

horz = extractClues( driver.findElements( org.openqa.selenium.By.xpath( '//div[@id=''sclue'']/img' ) ) );
vert = extractClues( driver.findElements( org.openqa.selenium.By.xpath( '//div[@id=''tclue'']/img' ) ) );

driver.close();

end
